### ISSUE TITLE
Server crash: `NoClassDefFoundError: requious/gui/slot/EnergySlot`

### ISSUE THREAD

**Issue by Krutoy242** [XHL315/IC2-No#1]
Seems like dedicated server can't run with this mod.

As far as world loaded and start ticking I get this error that crashing server:
```ruby
java.lang.NoClassDefFoundError: requious/gui/slot/EnergySlot
    at requious.data.component.ComponentEnergy.createSlot(ComponentEnergy.java:73)
    at requious.data.AssemblyProcessor.setComponent(AssemblyProcessor.java:312)
    at requious.data.AssemblyData.constructProcessor(AssemblyData.java:56)
    at requious.tile.TileEntityAssembly.initProcessor(TileEntityAssembly.java:205)
    [...]
Caused by: java.lang.ClassNotFoundException: requious.gui.slot.EnergySlot
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 16 more
```

[crash-2024-05-27_11.28.31-server.txt](https://github.com/XHL315/IC2-No/files/15455292/crash-2024-05-27_11.28.31-server.txt)

Removing mod IC2-No fixes the issue.

**Comment by XHL315** [comment]
I will try to fix it.

**Comment by Krutoy242** [comment]
Any luck on fixing?

**Comment by XHL315** [comment]
Unfortunately, I have no time to fix this bug during this period due to my school commitments.
So please waiting for me.
